### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by ekifox** [diamondio/better-queue#39] opened 2018-09-06 12:52 UTC
```javascript
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

const q = new Queue(async (input, cb) => {
  console.log(input)
  await sleep(1000)
  cb()
}, {
  concurrent: 3
})
```

Now I need to call in async callback functions. Can you do an automatic wait for asynchronous functions? To remove that callback

**Comment by LinusU** [comment] 2018-09-06 13:04
I would love a 4.x where all callbacks are replaced by Promises ☺️

**Comment by leanderlee** [comment] 2018-09-06 18:08
Me too! Anyone want to take a shot at it?

**Comment by leanderlee** [comment] 2018-09-06 18:09
Duplicate of #23

**Closed by leanderlee** 2018-09-06 18:09 UTC

**Comment by nombrekeff** [comment] 2019-06-13 21:24
> Me too! Anyone want to take a shot at it?

I might have a take on this!

**Comment by njinvozone** [comment] 2022-12-15 10:21
any update on 4.X ?

**Comment by beautyfree** [comment] 2024-12-03 17:18
still waiting
